name: MRP
version: '1.0'
main: hrusinski.mrp.MRP
api-version: '1.20'

commands:
  cardName:
    usage: /cardName {newName}

  cardSurname:
    usage: /cardName {newSurname}

  cardAge:
    usage: /cardName {newAge}

  cardGender:
    usage: /cardName {newGender}

  cardNationality:
    usage: /cardName {newNationality}

  Card:
    usage: /Card {player}/{empty}

  me:
    usage: /me {action}

  do:
    usage: /do {action}

  looc:
    usage: /do {text}

  announce:
    usage: /announce {text}

  try:
    usage: /try